apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-app
  name: developer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "list"]
    resourceNames: ["myapp"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
    resourceNames: ["mydb"]