version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    volumes:
      - db-data:/var/lib/mysql/data # for mysql db-> host:container
      - mongo-data:/data/db # for mongo db
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
volumes:
  db-data
  mongo-data:  #name reference to a volume defined
    driver: local
