---
- name: creating user
  gather_facts: no
  hosts: all
  become: true
  vars:
    user_name: modi

  tasks:
  - name: creating user {{ user_name }}
    user:
      name: "{{ user_name }}"

  - name: creating a directory
    file:
      path: /opt/{{user_name}}_dir
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: 0755
