---
- name: uninstalling multiple packages
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: uninstalling packages
      yum:
        name: ['wget', 'tree', 'telnet']
        state: absent
