---
- name: installing multiple packages
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: installing packages
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - git
        - wget
        - netstat
        - tree
        - make
        - gzip
        - telnet
