# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64
M2_HOME=/opt/apache-maven-3.9.3
M2=$M2_HOME/bin
PATH=$PATH:$JAVA_HOME:$M2_HOME:$M2
export PATH
# User specific environment and startup programs
