apiVersion: v1
kind: Service
metadata:
  namespace: nginx-dev
  name: my-service-clusterip
  labels:
    app: helloworld
spec:
  ports:
  - port: 8080
    targetPort: http-server
  selector:
    app: nginx-app-clusterip
  type: ClusterIP
