apiVersion: v1
kind: Service
metadata:
  namespace: nginx-dev
  name: my-service-lb
spec:
  selector:
    app: nginx-app-lb
  type: LoadBalancer
  ports:
  - nodePort: 31000
    port: 80
    targetPort: 80
